[versions]
# Plugins & Core
kotlin = "1.9.25"
springBoot = "3.5.9"
springDependencyManagement = "1.1.7"
swaggerUI = "3.0.1"
jjwt = "0.12.7"
kotlinLogging = "7.0.14"
apiChangeLog = "1.0.1"
sejongPortalLogin = "1.0.0"
httpLogging = "0.0.9"

[libraries]
# Spring Starter Web
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }

# JPA
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }

# Validation
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }

# Test
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

# Redis
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }

# Spring Security
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }

# Postgres
postgresql = { module = "org.postgresql:postgresql" }

# JSON
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }

# Kotlin
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

# Swagger UI
swagger-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "swaggerUI" }

# JJWT
jjwt = { module = "io.jsonwebtoken:jjwt", version.ref = "jjwt" }

# Kotlin Logging
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlinLogging" }

# Chuseok22 ApiChangeLog
api-change-log = { module = "com.chuseok22:ApiChangeLog", version.ref = "apiChangeLog" }

# Chuseok22 Sejong Portal Login
sejong-portal-login = { module = "com.chuseok22:sejong-portal-login", version.ref = "sejongPortalLogin" }

# Chuseok22 Logging
http-logging = { module = "com.chuseok22:logging", version.ref = "httpLogging" }


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
